server:
  port: 8080

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

app:
  upload:
    dir: uploads/avatars
